"""empty message

Revision ID: 1e318941a527
Revises: 
Create Date: 2023-01-30 02:14:44.215043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e318941a527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fountains', 'borough',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('fountains', 'details',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('fountains', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('fountains', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fountains', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fountains', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('fountains', 'geometry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fountains', sa.Column('geometry', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('fountains', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('fountains', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fountains', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fountains', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('fountains', 'details',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('fountains', 'borough',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
