"""empty message

Revision ID: c024f5412245
Revises: 
Create Date: 2023-02-03 17:23:30.265277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c024f5412245'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fountains',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('details', sa.String(), nullable=False),
                    sa.Column('borough', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('phone', sa.Integer(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fountains')
    # ### end Alembic commands ###
