"""empty message

Revision ID: d5a693b217d5
Revises: 
Create Date: 2023-01-30 15:49:33.083794

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 as gsa

# revision identifiers, used by Alembic.
revision = 'd5a693b217d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fountains',
    gsa.Column('id', sa.Integer(), nullable=False),
    gsa.Column('geometry', gsa.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    gsa.Column('name', sa.String(), nullable=False),
    gsa.Column('details', sa.String(), nullable=False),
    gsa.Column('borough', sa.String(), nullable=False),
    gsa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fountains_geometry', 'fountains', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fountains_geometry', table_name='fountains')
    op.drop_table('fountains')
    # ### end Alembic commands ###
